export enum TransferStatus {
  PENDING = 'PENDING',
  STARTING = 'STARTING',
  STARTED = 'STARTED',
  ONCHAIN_TRANSFER_DONE = 'ONCHAIN_TRANSFER_DONE',
  OFFRAMP_INIT = 'OFFRAMP_INIT',
  OFFRAMP_COMPLETED = 'OFFRAMP_COMPLETED',
  FAILED = 'FAILED',
}
